using SalesPlanning.Api.Contracts;

namespace SalesPlanning.Api.Application;

public interface IPlanningService
{
    Task<GridSliceResponse> GetGridSliceAsync(long scenarioVersionId, long? selectedStoreId, string? selectedDepartmentLabel, IReadOnlyCollection<long>? expandedProductNodeIds, bool expandAllBranches, CancellationToken cancellationToken);
    Task<EditCellsResponse> ApplyEditsAsync(EditCellsRequest request, string userId, CancellationToken cancellationToken);
    Task<SplashResponse> ApplySplashAsync(SplashRequest request, string userId, CancellationToken cancellationToken);
    Task<LockCellsResponse> ApplyLockAsync(LockCellsRequest request, string userId, CancellationToken cancellationToken);
    Task<IReadOnlyList<AuditTrailItemDto>> GetAuditAsync(long scenarioVersionId, long measureId, long storeId, long productNodeId, CancellationToken cancellationToken);
    Task<AddRowResponse> AddRowAsync(AddRowRequest request, CancellationToken cancellationToken);
    Task<DeleteEntityResponse> DeleteRowAsync(DeleteRowRequest request, CancellationToken cancellationToken);
    Task<DeleteEntityResponse> DeleteYearAsync(DeleteYearRequest request, CancellationToken cancellationToken);
    Task<GenerateNextYearResponse> GenerateNextYearAsync(GenerateNextYearRequest request, string userId, CancellationToken cancellationToken);
    Task<HierarchyMappingResponse> GetHierarchyMappingsAsync(CancellationToken cancellationToken);
    Task<HierarchyMappingResponse> AddHierarchyDepartmentAsync(AddHierarchyDepartmentRequest request, CancellationToken cancellationToken);
    Task<HierarchyMappingResponse> AddHierarchyClassAsync(AddHierarchyClassRequest request, CancellationToken cancellationToken);
    Task<HierarchyMappingResponse> AddHierarchySubclassAsync(AddHierarchySubclassRequest request, CancellationToken cancellationToken);
    Task<PlanningInsightResponse> GetPlanningInsightsAsync(long scenarioVersionId, long storeId, long productNodeId, long yearTimePeriodId, CancellationToken cancellationToken);
    Task<ApplyGrowthFactorResponse> ApplyGrowthFactorAsync(ApplyGrowthFactorRequest request, string userId, CancellationToken cancellationToken);
    Task<SaveScenarioResponse> SaveScenarioAsync(SaveScenarioRequest request, string userId, CancellationToken cancellationToken);
    Task<PlanningStoreScopeResponse> GetPlanningStoreScopesAsync(CancellationToken cancellationToken);
    Task<StoreProfileResponse> GetStoreProfilesAsync(CancellationToken cancellationToken);
    Task<StoreProfileDto> UpsertStoreProfileAsync(UpsertStoreProfileRequest request, CancellationToken cancellationToken);
    Task DeleteStoreProfileAsync(DeleteStoreProfileRequest request, CancellationToken cancellationToken);
    Task<StoreProfileDto> InactivateStoreProfileAsync(InactivateStoreProfileRequest request, CancellationToken cancellationToken);
    Task<StoreProfileOptionsResponse> GetStoreProfileOptionsAsync(CancellationToken cancellationToken);
    Task<StoreProfileOptionsResponse> UpsertStoreProfileOptionAsync(UpsertStoreProfileOptionRequest request, CancellationToken cancellationToken);
    Task<StoreProfileOptionsResponse> DeleteStoreProfileOptionAsync(DeleteStoreProfileOptionRequest request, CancellationToken cancellationToken);
    Task<StoreProfileImportResponse> ImportStoreProfilesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportStoreProfilesAsync(CancellationToken cancellationToken);
    Task<ProductProfileResponse> GetProductProfilesAsync(string? searchTerm, int pageNumber, int pageSize, CancellationToken cancellationToken);
    Task<ProductProfileDto> UpsertProductProfileAsync(UpsertProductProfileRequest request, CancellationToken cancellationToken);
    Task DeleteProductProfileAsync(DeleteProductProfileRequest request, CancellationToken cancellationToken);
    Task<ProductProfileDto> InactivateProductProfileAsync(InactivateProductProfileRequest request, CancellationToken cancellationToken);
    Task<ProductProfileOptionsResponse> GetProductProfileOptionsAsync(CancellationToken cancellationToken);
    Task<ProductProfileOptionsResponse> UpsertProductProfileOptionAsync(UpsertProductProfileOptionRequest request, CancellationToken cancellationToken);
    Task<ProductProfileOptionsResponse> DeleteProductProfileOptionAsync(DeleteProductProfileOptionRequest request, CancellationToken cancellationToken);
    Task<ProductHierarchyResponse> GetProductHierarchyCatalogAsync(CancellationToken cancellationToken);
    Task<ProductHierarchyResponse> UpsertProductHierarchyCatalogAsync(UpsertProductHierarchyRequest request, CancellationToken cancellationToken);
    Task<ProductHierarchyResponse> DeleteProductHierarchyCatalogAsync(DeleteProductHierarchyRequest request, CancellationToken cancellationToken);
    Task<ProductProfileImportResponse> ImportProductProfilesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportProductProfilesAsync(CancellationToken cancellationToken);
    Task<InventoryProfileResponse> GetInventoryProfilesAsync(string? searchTerm, int pageNumber, int pageSize, CancellationToken cancellationToken);
    Task<InventoryProfileDto> UpsertInventoryProfileAsync(UpsertInventoryProfileRequest request, CancellationToken cancellationToken);
    Task DeleteInventoryProfileAsync(DeleteInventoryProfileRequest request, CancellationToken cancellationToken);
    Task<InventoryProfileDto> InactivateInventoryProfileAsync(InactivateInventoryProfileRequest request, CancellationToken cancellationToken);
    Task<InventoryProfileImportResponse> ImportInventoryProfilesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportInventoryProfilesAsync(CancellationToken cancellationToken);
    Task<PricingPolicyResponse> GetPricingPoliciesAsync(string? searchTerm, int pageNumber, int pageSize, CancellationToken cancellationToken);
    Task<PricingPolicyDto> UpsertPricingPolicyAsync(UpsertPricingPolicyRequest request, CancellationToken cancellationToken);
    Task DeletePricingPolicyAsync(DeletePricingPolicyRequest request, CancellationToken cancellationToken);
    Task<PricingPolicyDto> InactivatePricingPolicyAsync(InactivatePricingPolicyRequest request, CancellationToken cancellationToken);
    Task<PricingPolicyImportResponse> ImportPricingPoliciesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportPricingPoliciesAsync(CancellationToken cancellationToken);
    Task<SeasonalityEventProfileResponse> GetSeasonalityEventProfilesAsync(string? searchTerm, int pageNumber, int pageSize, CancellationToken cancellationToken);
    Task<SeasonalityEventProfileDto> UpsertSeasonalityEventProfileAsync(UpsertSeasonalityEventProfileRequest request, CancellationToken cancellationToken);
    Task DeleteSeasonalityEventProfileAsync(DeleteSeasonalityEventProfileRequest request, CancellationToken cancellationToken);
    Task<SeasonalityEventProfileDto> InactivateSeasonalityEventProfileAsync(InactivateSeasonalityEventProfileRequest request, CancellationToken cancellationToken);
    Task<SeasonalityEventProfileImportResponse> ImportSeasonalityEventProfilesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportSeasonalityEventProfilesAsync(CancellationToken cancellationToken);
    Task<VendorSupplyProfileResponse> GetVendorSupplyProfilesAsync(string? searchTerm, int pageNumber, int pageSize, CancellationToken cancellationToken);
    Task<VendorSupplyProfileDto> UpsertVendorSupplyProfileAsync(UpsertVendorSupplyProfileRequest request, CancellationToken cancellationToken);
    Task DeleteVendorSupplyProfileAsync(DeleteVendorSupplyProfileRequest request, CancellationToken cancellationToken);
    Task<VendorSupplyProfileDto> InactivateVendorSupplyProfileAsync(InactivateVendorSupplyProfileRequest request, CancellationToken cancellationToken);
    Task<VendorSupplyProfileImportResponse> ImportVendorSupplyProfilesAsync(Stream workbookStream, string fileName, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportVendorSupplyProfilesAsync(CancellationToken cancellationToken);
    Task<ImportWorkbookResponse> ImportWorkbookAsync(long scenarioVersionId, Stream workbookStream, string fileName, string userId, CancellationToken cancellationToken);
    Task<(byte[] Content, string FileName)> ExportWorkbookAsync(long scenarioVersionId, CancellationToken cancellationToken);
    Task ResetAsync(CancellationToken cancellationToken);
}
